/**
 * BIA — Biblioteca de Biomateriais para Bioimpressão
 * =====================================================
 * Catálogo curado dos 30 biomateriais mais usados na biofabricação de tecidos
 * que funcionalizarão no corpo humano (com difusão molecular adequada).
 *
 * Cada material inclui:
 *  - Concentração típica (% m/v)
 *  - Mecanismo de reticulação (crosslinking)
 *  - Módulo elástico típico (kPa)
 *  - Tamanho de poro / difusão (Folkman <200 µm)
 *  - Tecidos-alvo e referências-chave
 *  - Compatibilidade de impressão (extrusion / DLP / inkjet)
 */

export type CrosslinkMechanism =
  | "ionic"          // Ca²⁺, Ba²⁺
  | "photo_UV"       // UV 365 nm
  | "photo_visible"  // LAP, Ru/SPS (405/450 nm)
  | "thermal"        // T-induced (col, agarose, Matrigel)
  | "enzymatic"      // transglutaminase, trombina
  | "physical"       // H-bonds, self-assembly
  | "chemical"       // EDC/NHS, genipin

export type PrintingMethod = "extrusion" | "DLP_SLA" | "inkjet" | "aerosol"

export interface Biomaterial {
  id: string
  name: string
  shortName: string
  category: "natural" | "synthetic" | "decellularized" | "composite"
  family: string           // "Alginate", "GelMA", "Collagen"...
  description: string
  concentrationRange: { min: number; max: number; typical: number; unit: string }  // % m/v
  crosslink: CrosslinkMechanism[]
  modulus_kPa: { min: number; max: number }   // Módulo de Young típico
  poreSize_um: { min: number; max: number }    // após reticulação
  diffusionCoeff?: string                       // qualitativo
  printability: PrintingMethod[]
  viscosity_Pas?: { min: number; max: number }  // a 37°C / shear baixo
  cellViability_24h_pct: number                 // viabilidade 24h típica (%)
  tissueApplications: string[]
  keyReferences: string[]
  pros: string[]
  cons: string[]
  typicalPartners?: string[]                    // bioinks que combinam bem
  costTier: "low" | "medium" | "high" | "premium"
  regulatoryStatus?: string                     // "FDA-approved for X", "research only"...
  icon: string
}

export const BIOMATERIALS: Biomaterial[] = [
  // ═══════════════════════════════════════════════════════════
  // HIDROGÉIS NATURAIS — POLISSACARÍDEOS
  // ═══════════════════════════════════════════════════════════
  {
    id: "alginate",
    name: "Alginato de Sódio",
    shortName: "Alginate",
    category: "natural",
    family: "Alginate",
    description: "Polissacarídeo aniônico extraído de algas marrons; reticula com Ca²⁺ formando hidrogel instantâneo ('egg-box')",
    concentrationRange: { min: 1, max: 8, typical: 3, unit: "% m/v" },
    crosslink: ["ionic"],
    modulus_kPa: { min: 5, max: 50 },
    poreSize_um: { min: 5, max: 200 },
    diffusionCoeff: "Alta para moléculas <70 kDa",
    printability: ["extrusion", "inkjet"],
    viscosity_Pas: { min: 0.1, max: 5 },
    cellViability_24h_pct: 85,
    tissueApplications: ["Encapsulamento de ilhotas pancreáticas", "Cartilagem", "Vasos pequenos"],
    keyReferences: ["Rowley 1999 Biomaterials", "Lee & Mooney 2012 Prog Polym Sci"],
    pros: ["Gelificação instantânea", "Biocompatível", "Baixo custo", "Fácil esterilização"],
    cons: ["Sem motivos de adesão celular (RGD necessário)", "Degradação descontrolada"],
    typicalPartners: ["gelma", "collagen_I", "gelatin"],
    costTier: "low",
    regulatoryStatus: "FDA-approved (wound care)",
    icon: "🌊",
  },
  {
    id: "chitosan",
    name: "Quitosana",
    shortName: "Chitosan",
    category: "natural",
    family: "Chitosan",
    description: "Polímero catiônico derivado da quitina; antibacteriano, bioadesivo, reticula por pH alcalino",
    concentrationRange: { min: 1, max: 4, typical: 2, unit: "% m/v" },
    crosslink: ["physical", "chemical", "ionic"],
    modulus_kPa: { min: 10, max: 100 },
    poreSize_um: { min: 10, max: 200 },
    diffusionCoeff: "Moderada",
    printability: ["extrusion"],
    viscosity_Pas: { min: 0.5, max: 20 },
    cellViability_24h_pct: 80,
    tissueApplications: ["Pele", "Curativos antibacterianos", "Osso (com HA)", "Cartilagem"],
    keyReferences: ["Kim 2008 Biotechnol Adv", "Croisier 2013 Eur Polym J"],
    pros: ["Antibacteriano intrínseco", "Mucoadesivo", "Promove coagulação"],
    cons: ["Solúvel apenas em meio ácido", "Variabilidade lote-a-lote"],
    typicalPartners: ["hydroxyapatite", "collagen_I", "gelatin"],
    costTier: "low",
    icon: "🦐",
  },
  {
    id: "hyaluronic_acid",
    name: "Ácido Hialurônico",
    shortName: "HA",
    category: "natural",
    family: "GAG",
    description: "Glicosaminoglicano natural; componente chave da MEC, lubrificante articular e regulador de hidratação",
    concentrationRange: { min: 0.5, max: 5, typical: 2, unit: "% m/v" },
    crosslink: ["photo_UV", "photo_visible", "chemical", "enzymatic"],
    modulus_kPa: { min: 1, max: 30 },
    poreSize_um: { min: 50, max: 500 },
    diffusionCoeff: "Alta (retém água)",
    printability: ["extrusion", "DLP_SLA", "inkjet"],
    viscosity_Pas: { min: 1, max: 100 },
    cellViability_24h_pct: 90,
    tissueApplications: ["Cartilagem articular", "Pele/derme", "Olho (vítreo)", "Cordas vocais"],
    keyReferences: ["Burdick & Prestwich 2011 Adv Mater", "Highley 2015 Adv Mater"],
    pros: ["Nativo do corpo humano", "Alta hidratação", "Receptores CD44"],
    cons: ["Degradação rápida (hialuronidases)", "Caro", "Baixa resistência mecânica"],
    typicalPartners: ["gelma", "collagen_II", "pegda"],
    costTier: "medium",
    regulatoryStatus: "FDA-approved (dermal fillers, viscosupplementation)",
    icon: "💧",
  },
  {
    id: "agarose",
    name: "Agarose",
    shortName: "Agarose",
    category: "natural",
    family: "Agarose",
    description: "Polissacarídeo termoreversível extraído de algas vermelhas; gelifica por resfriamento",
    concentrationRange: { min: 0.5, max: 4, typical: 1.5, unit: "% m/v" },
    crosslink: ["thermal", "physical"],
    modulus_kPa: { min: 10, max: 200 },
    poreSize_um: { min: 50, max: 300 },
    diffusionCoeff: "Alta para <50 kDa",
    printability: ["extrusion"],
    cellViability_24h_pct: 78,
    tissueApplications: ["Cartilagem", "Neural (scaffolds)", "Organoids support"],
    keyReferences: ["Campos 2013 Biofabrication", "Duarte-Campos 2012"],
    pros: ["Gelificação térmica simples", "Reprodutível", "Baixo custo"],
    cons: ["Bioinerte (sem motivos de adesão)", "Difícil degradação in vivo"],
    typicalPartners: ["collagen_I", "fibrinogen"],
    costTier: "low",
    icon: "🧫",
  },
  {
    id: "pectin",
    name: "Pectina",
    shortName: "Pectin",
    category: "natural",
    family: "Pectin",
    description: "Polissacarídeo de frutas cítricas; reticula com Ca²⁺ (similar ao alginato); baixo custo",
    concentrationRange: { min: 2, max: 8, typical: 4, unit: "% m/v" },
    crosslink: ["ionic"],
    modulus_kPa: { min: 2, max: 20 },
    poreSize_um: { min: 10, max: 200 },
    printability: ["extrusion"],
    cellViability_24h_pct: 82,
    tissueApplications: ["Cartilagem", "Carreamento de fármacos", "Pele"],
    keyReferences: ["Munarin 2012 Int J Biol Macromol"],
    pros: ["Baixo custo", "Não-imunogênica", "Veganamente sustentável"],
    cons: ["Propriedades mecânicas baixas", "Variabilidade"],
    typicalPartners: ["alginate", "gelatin"],
    costTier: "low",
    icon: "🍊",
  },

  // ═══════════════════════════════════════════════════════════
  // PROTEÍNAS NATURAIS
  // ═══════════════════════════════════════════════════════════
  {
    id: "collagen_I",
    name: "Colágeno Tipo I",
    shortName: "Col-I",
    category: "natural",
    family: "Collagen",
    description: "Proteína estrutural mais abundante do corpo humano (90% do colágeno total); fibrilas auto-montadas",
    concentrationRange: { min: 0.1, max: 2, typical: 0.5, unit: "% m/v (1-20 mg/mL)" },
    crosslink: ["thermal", "physical", "chemical", "enzymatic"],
    modulus_kPa: { min: 0.1, max: 10 },
    poreSize_um: { min: 1, max: 100 },
    diffusionCoeff: "Alta",
    printability: ["extrusion", "inkjet"],
    viscosity_Pas: { min: 0.01, max: 1 },
    cellViability_24h_pct: 95,
    tissueApplications: ["Pele/derme", "Osso", "Tendão", "Córnea", "Vascularização"],
    keyReferences: ["Lee 2014 Science 365", "FRESH method Feinberg 2019"],
    pros: ["Nativo humano", "Motivos RGD naturais", "FDA-approved"],
    cons: ["Baixa resistência mecânica", "Degradação rápida", "pH/T sensível"],
    typicalPartners: ["gelma", "hyaluronic_acid", "fibrinogen"],
    costTier: "medium",
    regulatoryStatus: "FDA-approved",
    icon: "🧬",
  },
  {
    id: "collagen_II",
    name: "Colágeno Tipo II",
    shortName: "Col-II",
    category: "natural",
    family: "Collagen",
    description: "Colágeno predominante em cartilagem hialina; fibrilas finas para meio pericelular",
    concentrationRange: { min: 0.1, max: 1, typical: 0.3, unit: "% m/v" },
    crosslink: ["thermal", "chemical"],
    modulus_kPa: { min: 0.1, max: 5 },
    poreSize_um: { min: 5, max: 50 },
    printability: ["extrusion"],
    cellViability_24h_pct: 92,
    tissueApplications: ["Cartilagem articular", "Disco intervertebral", "Vítreo ocular"],
    keyReferences: ["Yang 2017 Acta Biomater"],
    pros: ["Específico para cartilagem", "Promove condrogênese"],
    cons: ["Custo alto", "Extração complexa", "Auto-montagem lenta"],
    typicalPartners: ["hyaluronic_acid", "chondroitin_sulfate"],
    costTier: "high",
    icon: "🦴",
  },
  {
    id: "gelatin",
    name: "Gelatina",
    shortName: "Gelatin",
    category: "natural",
    family: "Collagen-derived",
    description: "Colágeno desnaturado hidrolisado; mantém motivos RGD; gelifica por resfriamento",
    concentrationRange: { min: 3, max: 15, typical: 10, unit: "% m/v" },
    crosslink: ["thermal", "enzymatic", "chemical"],
    modulus_kPa: { min: 1, max: 30 },
    poreSize_um: { min: 10, max: 200 },
    printability: ["extrusion", "inkjet"],
    viscosity_Pas: { min: 0.5, max: 50 },
    cellViability_24h_pct: 88,
    tissueApplications: ["Pele", "Vascular", "Tecidos moles gerais", "Suporte de sacrifício (FRESH)"],
    keyReferences: ["Wang 2017 Biofabrication", "Hinton 2015 Sci Adv"],
    pros: ["Barata", "RGD preservado", "Fácil obtenção"],
    cons: ["Termicamente instável (derrete >37°C)", "Necessita crosslinker"],
    typicalPartners: ["gelma", "fibrinogen", "alginate"],
    costTier: "low",
    icon: "🍮",
  },
  {
    id: "gelma",
    name: "Gelatina Metacrilada (GelMA)",
    shortName: "GelMA",
    category: "natural",
    family: "Collagen-derived",
    description: "Gelatina funcionalizada com grupos metacrilato; foto-reticulável (UV/visível), mantém bioatividade",
    concentrationRange: { min: 3, max: 20, typical: 10, unit: "% m/v" },
    crosslink: ["photo_UV", "photo_visible"],
    modulus_kPa: { min: 1, max: 100 },
    poreSize_um: { min: 5, max: 150 },
    diffusionCoeff: "Alta (ajustável pelo grau de metacrilação)",
    printability: ["extrusion", "DLP_SLA", "inkjet"],
    viscosity_Pas: { min: 0.1, max: 20 },
    cellViability_24h_pct: 90,
    tissueApplications: ["Pele", "Cartilagem", "Vascular", "Neural", "Cardíaco", "Fígado"],
    keyReferences: ["Yue 2015 Biomaterials", "Loessner 2016 Nat Protoc"],
    pros: ["Versátil", "Bioativa (motivos RGD, MMP-degradável)", "Bem caracterizado", "Tunável"],
    cons: ["Requer UV/visível + fotoiniciador", "Degradação por MMPs pode ser muito rápida"],
    typicalPartners: ["hyaluronic_acid", "pegda", "alginate", "collagen_I"],
    costTier: "medium",
    icon: "✨",
  },
  {
    id: "fibrinogen",
    name: "Fibrinogênio/Fibrina",
    shortName: "Fibrin",
    category: "natural",
    family: "Fibrin",
    description: "Precursor solúvel que a trombina converte em fibrina (rede 3D); chave na cicatrização",
    concentrationRange: { min: 1, max: 5, typical: 2, unit: "% m/v" },
    crosslink: ["enzymatic"],
    modulus_kPa: { min: 0.1, max: 5 },
    poreSize_um: { min: 1, max: 50 },
    printability: ["extrusion", "inkjet"],
    cellViability_24h_pct: 92,
    tissueApplications: ["Vascular", "Neural", "Cicatrização", "Cardíaco", "Pele"],
    keyReferences: ["Ahmed 2008 Tissue Eng B"],
    pros: ["Autólogo (do próprio paciente)", "Bioativo", "FDA-approved"],
    cons: ["Propriedades mecânicas baixas", "Degradação rápida"],
    typicalPartners: ["collagen_I", "gelatin", "alginate"],
    costTier: "medium",
    regulatoryStatus: "FDA-approved (surgical sealant)",
    icon: "🩸",
  },
  {
    id: "silk_fibroin",
    name: "Fibroína de Seda",
    shortName: "Silk",
    category: "natural",
    family: "Silk",
    description: "Proteína da seda do bicho-da-seda (Bombyx mori); excelentes propriedades mecânicas, auto-montagem β-sheet",
    concentrationRange: { min: 3, max: 15, typical: 6, unit: "% m/v" },
    crosslink: ["physical", "enzymatic", "photo_visible"],
    modulus_kPa: { min: 50, max: 3000 },
    poreSize_um: { min: 1, max: 100 },
    printability: ["extrusion", "DLP_SLA"],
    cellViability_24h_pct: 85,
    tissueApplications: ["Osso", "Cartilagem", "Ligamento/tendão", "Córnea", "Vascular"],
    keyReferences: ["Kundu 2013 Adv Drug Deliv Rev", "Rockwood 2011 Nat Protoc"],
    pros: ["Alta resistência", "Degradação lenta controlável", "FDA-approved"],
    cons: ["Processamento complexo", "Gelificação lenta"],
    typicalPartners: ["gelma", "hydroxyapatite", "chitosan"],
    costTier: "medium",
    regulatoryStatus: "FDA-approved (sutures)",
    icon: "🪢",
  },
  {
    id: "elastin",
    name: "Elastina",
    shortName: "Elastin",
    category: "natural",
    family: "Elastin",
    description: "Proteína elastomérica responsável pela recuperação de tecidos (pele, pulmão, vasos); tropoelastina",
    concentrationRange: { min: 1, max: 10, typical: 5, unit: "% m/v" },
    crosslink: ["enzymatic", "chemical", "photo_UV"],
    modulus_kPa: { min: 10, max: 500 },
    poreSize_um: { min: 1, max: 50 },
    printability: ["extrusion", "DLP_SLA"],
    cellViability_24h_pct: 87,
    tissueApplications: ["Vasos sanguíneos", "Pele", "Pulmão", "Cordas vocais"],
    keyReferences: ["Annabi 2017 Adv Healthc Mater"],
    pros: ["Propriedades elastoméricas", "Bioativa"],
    cons: ["Cara", "Imunogenicidade", "Produção complexa"],
    typicalPartners: ["collagen_I", "gelma"],
    costTier: "premium",
    icon: "🎗️",
  },
  {
    id: "matrigel",
    name: "Matrigel™ / MEC Engelbreth",
    shortName: "Matrigel",
    category: "natural",
    family: "MEC complex",
    description: "MEC de tumor Engelbreth-Holm-Swarm (laminina, col-IV, perlecano); padrão-ouro para organoides",
    concentrationRange: { min: 30, max: 100, typical: 80, unit: "% v/v (como-solubilizado)" },
    crosslink: ["thermal"],
    modulus_kPa: { min: 0.1, max: 1 },
    poreSize_um: { min: 1, max: 20 },
    printability: ["extrusion", "inkjet"],
    cellViability_24h_pct: 95,
    tissueApplications: ["Organoides (intestinais, cerebrais, hepáticos)", "Câncer 3D", "Membrana basal"],
    keyReferences: ["Sato 2011 Gastroenterology", "Kleinman 2005 Semin Cancer Biol"],
    pros: ["Muito bioativa (fatores de crescimento)", "Padrão-ouro para organoides"],
    cons: ["Origem tumoral murina", "Variabilidade lote-a-lote", "Não-GMP"],
    typicalPartners: ["collagen_I"],
    costTier: "premium",
    icon: "🧠",
  },

  // ═══════════════════════════════════════════════════════════
  // DECELULARIZADAS (dECM)
  // ═══════════════════════════════════════════════════════════
  {
    id: "decm_cardiac",
    name: "dECM Cardíaca",
    shortName: "dECM-Heart",
    category: "decellularized",
    family: "dECM",
    description: "MEC cardíaca descelularizada; retém composição proteica e bioativa específica do tecido",
    concentrationRange: { min: 1, max: 4, typical: 2, unit: "% m/v (liofilizada)" },
    crosslink: ["thermal", "photo_UV"],
    modulus_kPa: { min: 1, max: 50 },
    poreSize_um: { min: 5, max: 100 },
    printability: ["extrusion"],
    cellViability_24h_pct: 90,
    tissueApplications: ["Patch cardíaco", "Regeneração miocárdica"],
    keyReferences: ["Pati 2014 Nat Commun", "Singelyn 2012 JACC"],
    pros: ["Sinais bioespecíficos do tecido nativo", "Promove diferenciação CM"],
    cons: ["Variabilidade", "Protocolos GMP complexos"],
    typicalPartners: ["gelma"],
    costTier: "high",
    icon: "❤️",
  },
  {
    id: "decm_skin",
    name: "dECM Dérmica",
    shortName: "dECM-Skin",
    category: "decellularized",
    family: "dECM",
    description: "MEC dérmica descelularizada; rica em colágeno I/III, elastina, proteoglicanos",
    concentrationRange: { min: 1, max: 5, typical: 3, unit: "% m/v" },
    crosslink: ["thermal", "enzymatic"],
    modulus_kPa: { min: 1, max: 30 },
    poreSize_um: { min: 5, max: 150 },
    printability: ["extrusion"],
    cellViability_24h_pct: 91,
    tissueApplications: ["Pele", "Queimaduras", "Curativos bioativos"],
    keyReferences: ["Pati 2014 Nat Commun"],
    pros: ["Específica do tecido", "Preserva fatores de crescimento"],
    cons: ["Custo elevado", "Regulamentação complexa"],
    typicalPartners: ["collagen_I", "gelma"],
    costTier: "high",
    icon: "🫳",
  },

  // ═══════════════════════════════════════════════════════════
  // POLÍMEROS SINTÉTICOS
  // ═══════════════════════════════════════════════════════════
  {
    id: "pegda",
    name: "Poli(etileno glicol) Diacrilato",
    shortName: "PEGDA",
    category: "synthetic",
    family: "PEG",
    description: "PEG funcionalizado com acrilato em ambas extremidades; foto-reticulável, alta reprodutibilidade",
    concentrationRange: { min: 5, max: 40, typical: 15, unit: "% m/v" },
    crosslink: ["photo_UV", "photo_visible"],
    modulus_kPa: { min: 10, max: 1000 },
    poreSize_um: { min: 1, max: 50 },
    diffusionCoeff: "Ajustável por MW do PEG",
    printability: ["DLP_SLA", "extrusion", "inkjet"],
    cellViability_24h_pct: 75,
    tissueApplications: ["Cartilagem", "Osso (com HA)", "Microfluidica", "Lentes"],
    keyReferences: ["Lin 2013 Biomaterials", "Grigoryan 2019 Science"],
    pros: ["Altamente reprodutível", "Propriedades ajustáveis", "GMP-friendly"],
    cons: ["Bioinerte (precisa de RGD)", "Fotoiniciador pode ser citotóxico"],
    typicalPartners: ["gelma", "hyaluronic_acid", "rgd_peptide"],
    costTier: "medium",
    icon: "⚗️",
  },
  {
    id: "pcl",
    name: "Policaprolactona",
    shortName: "PCL",
    category: "synthetic",
    family: "Polyester",
    description: "Poliéster termoplástico biodegradável; usado em scaffolds estruturais (FDM)",
    concentrationRange: { min: 60, max: 100, typical: 100, unit: "% (termofusão)" },
    crosslink: ["thermal"],
    modulus_kPa: { min: 50000, max: 400000 },
    poreSize_um: { min: 100, max: 1000 },
    printability: ["extrusion"],
    cellViability_24h_pct: 70,
    tissueApplications: ["Osso", "Cartilagem (estrutural)", "Vascular (grande calibre)", "Scaffold externo"],
    keyReferences: ["Woodruff & Hutmacher 2010 Prog Polym Sci"],
    pros: ["Biodegradável (2-4 anos)", "Mecanicamente resistente", "FDA-approved"],
    cons: ["Hidrofóbico (baixa adesão celular)", "Fusão a 60°C (incompatível com células)"],
    typicalPartners: ["gelma", "collagen_I", "hydroxyapatite"],
    costTier: "low",
    regulatoryStatus: "FDA-approved",
    icon: "🏗️",
  },
  {
    id: "plga",
    name: "Poli(ácido lático-co-glicólico)",
    shortName: "PLGA",
    category: "synthetic",
    family: "Polyester",
    description: "Copolímero biodegradável de PLA e PGA; degradação ajustável pela razão LA:GA",
    concentrationRange: { min: 5, max: 20, typical: 10, unit: "% m/v (em DMSO/DMF)" },
    crosslink: ["thermal"],
    modulus_kPa: { min: 1000, max: 2000000 },
    poreSize_um: { min: 50, max: 500 },
    printability: ["extrusion", "DLP_SLA"],
    cellViability_24h_pct: 65,
    tissueApplications: ["Osso", "Liberação controlada de fármacos", "Suturas"],
    keyReferences: ["Makadia & Siegel 2011 Polymers"],
    pros: ["Degradação ajustável (semanas a meses)", "FDA-approved"],
    cons: ["Solventes orgânicos tóxicos no processamento", "pH ácido na degradação"],
    typicalPartners: ["hydroxyapatite", "collagen_I"],
    costTier: "medium",
    regulatoryStatus: "FDA-approved",
    icon: "🧪",
  },
  {
    id: "pluronic",
    name: "Pluronic® F-127",
    shortName: "Pluronic",
    category: "synthetic",
    family: "Block copolymer",
    description: "Copolímero PEO-PPO-PEO; gelifica com aumento de temperatura (LCST); usado como bioink de sacrifício",
    concentrationRange: { min: 20, max: 40, typical: 30, unit: "% m/v" },
    crosslink: ["thermal", "physical"],
    modulus_kPa: { min: 1, max: 20 },
    poreSize_um: { min: 100, max: 1000 },
    printability: ["extrusion"],
    cellViability_24h_pct: 50,
    tissueApplications: ["Sacrifício (molde vascular)", "Canais removíveis"],
    keyReferences: ["Kolesky 2014 Adv Mater"],
    pros: ["Termorreversível", "Facilita vascularização por dissolução"],
    cons: ["Tóxico para células se não removido", "Sem estrutura celular"],
    typicalPartners: ["gelma", "collagen_I"],
    costTier: "low",
    icon: "🌡️",
  },
  {
    id: "pva",
    name: "Poli(álcool vinílico)",
    shortName: "PVA",
    category: "synthetic",
    family: "Vinyl",
    description: "Polímero hidrofílico solúvel em água; reticulação por ciclos freeze-thaw",
    concentrationRange: { min: 5, max: 20, typical: 10, unit: "% m/v" },
    crosslink: ["physical", "chemical"],
    modulus_kPa: { min: 10, max: 200 },
    poreSize_um: { min: 1, max: 100 },
    printability: ["extrusion", "inkjet"],
    cellViability_24h_pct: 75,
    tissueApplications: ["Cartilagem", "Material de sacrifício", "Lente de contato"],
    keyReferences: ["Baker 2012 Biomed Mater"],
    pros: ["Barato", "Transparente", "Processável em água"],
    cons: ["Sem motivos de adesão celular", "Não-degradável in vivo"],
    typicalPartners: ["collagen_I", "gelma"],
    costTier: "low",
    icon: "💎",
  },
  {
    id: "polyurethane",
    name: "Poliuretano (TPU biomédico)",
    shortName: "TPU",
    category: "synthetic",
    family: "Polyurethane",
    description: "Elastômero biocompatível com alta flexibilidade; adequado para vasos e válvulas",
    concentrationRange: { min: 10, max: 30, typical: 20, unit: "% m/v" },
    crosslink: ["chemical", "photo_UV"],
    modulus_kPa: { min: 1000, max: 100000 },
    poreSize_um: { min: 10, max: 200 },
    printability: ["extrusion", "DLP_SLA"],
    cellViability_24h_pct: 70,
    tissueApplications: ["Vascular (válvulas)", "Cardíaco", "Cartilagem"],
    keyReferences: ["Hung 2014 J Mech Behav Biomed Mater"],
    pros: ["Elastomérico", "Resistente à fadiga"],
    cons: ["Requer solventes", "Não totalmente biodegradável"],
    typicalPartners: ["pcl", "collagen_I"],
    costTier: "medium",
    icon: "🫀",
  },

  // ═══════════════════════════════════════════════════════════
  // COMPÓSITOS E ADITIVOS
  // ═══════════════════════════════════════════════════════════
  {
    id: "hydroxyapatite",
    name: "Hidroxiapatita",
    shortName: "HA (mineral)",
    category: "composite",
    family: "Ceramic",
    description: "Ca₁₀(PO₄)₆(OH)₂ — componente mineral do osso; cristais nanométricos promovem osteocondução",
    concentrationRange: { min: 5, max: 60, typical: 20, unit: "% m/v (partículas)" },
    crosslink: ["physical"],
    modulus_kPa: { min: 100000, max: 10000000 },
    poreSize_um: { min: 1, max: 500 },
    printability: ["extrusion", "DLP_SLA"],
    cellViability_24h_pct: 85,
    tissueApplications: ["Osso", "Dente", "Enxertos ortopédicos"],
    keyReferences: ["LeGeros 2002 Clin Orthop", "Ambard 2006 J Prosthodont"],
    pros: ["Osteocondutor", "Biocompatível", "FDA-approved"],
    cons: ["Frágil isoladamente", "Difícil de imprimir puro"],
    typicalPartners: ["pcl", "plga", "gelma", "collagen_I", "chitosan"],
    costTier: "low",
    regulatoryStatus: "FDA-approved",
    icon: "🦷",
  },
  {
    id: "tcp",
    name: "Beta-Tricálcio Fosfato",
    shortName: "β-TCP",
    category: "composite",
    family: "Ceramic",
    description: "Fosfato de cálcio biodegradável; promove osteocondução com reabsorção mais rápida que HA",
    concentrationRange: { min: 5, max: 60, typical: 20, unit: "% m/v" },
    crosslink: ["physical"],
    modulus_kPa: { min: 50000, max: 5000000 },
    poreSize_um: { min: 100, max: 500 },
    printability: ["extrusion", "DLP_SLA"],
    cellViability_24h_pct: 85,
    tissueApplications: ["Osso (regeneração rápida)", "Alveolar", "Craniofacial"],
    keyReferences: ["Bohner 2013 Biomaterials"],
    pros: ["Osteocondutor", "Reabsorção ajustável", "FDA-approved"],
    cons: ["Mecanicamente frágil"],
    typicalPartners: ["pcl", "collagen_I", "gelma"],
    costTier: "low",
    regulatoryStatus: "FDA-approved",
    icon: "🦴",
  },
  {
    id: "bioactive_glass",
    name: "Vidro Bioativo (45S5)",
    shortName: "BG 45S5",
    category: "composite",
    family: "Ceramic",
    description: "Vidro de silicato cálcio-fosfato (Bioglass®); forma apatita in situ; angiogênico",
    concentrationRange: { min: 5, max: 50, typical: 20, unit: "% m/v" },
    crosslink: ["physical"],
    modulus_kPa: { min: 30000, max: 300000 },
    poreSize_um: { min: 100, max: 500 },
    printability: ["extrusion"],
    cellViability_24h_pct: 82,
    tissueApplications: ["Osso", "Vascularização", "Cicatrização de pele"],
    keyReferences: ["Jones 2013 Acta Biomater", "Hench 1971"],
    pros: ["Osteocondutor + angiogênico", "Libera Ca/Si (sinalização)"],
    cons: ["pH elevado inicial", "Frágil"],
    typicalPartners: ["pcl", "gelma", "collagen_I"],
    costTier: "medium",
    regulatoryStatus: "FDA-approved (dental, bone graft)",
    icon: "🔮",
  },
  {
    id: "graphene_oxide",
    name: "Óxido de Grafeno",
    shortName: "GO",
    category: "composite",
    family: "Carbon",
    description: "Nanofolhas de grafeno oxidado; melhora propriedades mecânicas e elétricas do hidrogel",
    concentrationRange: { min: 0.01, max: 2, typical: 0.1, unit: "% m/v" },
    crosslink: ["physical"],
    modulus_kPa: { min: 100, max: 5000 },
    poreSize_um: { min: 1, max: 100 },
    printability: ["extrusion", "DLP_SLA"],
    cellViability_24h_pct: 80,
    tissueApplications: ["Neural", "Cardíaco", "Osso", "Sensores biomédicos"],
    keyReferences: ["Shin 2016 Adv Mater", "Wang 2019 Biomaterials"],
    pros: ["Condutividade elétrica", "Reforço mecânico em baixas %"],
    cons: ["Citotoxicidade dose-dependente", "Regulatório incerto"],
    typicalPartners: ["gelma", "alginate", "collagen_I"],
    costTier: "medium",
    icon: "⚡",
  },
  {
    id: "cnc",
    name: "Nanocelulose Cristalina",
    shortName: "CNC",
    category: "composite",
    family: "Cellulose",
    description: "Nanocristais de celulose; reforço mecânico em hidrogéis; alta razão de aspecto",
    concentrationRange: { min: 0.5, max: 5, typical: 2, unit: "% m/v" },
    crosslink: ["physical"],
    modulus_kPa: { min: 10, max: 1000 },
    poreSize_um: { min: 1, max: 100 },
    printability: ["extrusion"],
    cellViability_24h_pct: 85,
    tissueApplications: ["Cartilagem", "Pele", "Osso (com HA)"],
    keyReferences: ["Markstedt 2015 Biomacromolecules"],
    pros: ["Sustentável", "Melhora shear-thinning", "Reforço mecânico"],
    cons: ["Não-degradável em humanos", "Sem motivos de adesão"],
    typicalPartners: ["alginate", "gelma"],
    costTier: "medium",
    icon: "🌱",
  },

  // ═══════════════════════════════════════════════════════════
  // BIOMATERIAIS ESPECIALIZADOS
  // ═══════════════════════════════════════════════════════════
  {
    id: "chondroitin_sulfate",
    name: "Sulfato de Condroitina",
    shortName: "CS",
    category: "natural",
    family: "GAG",
    description: "GAG sulfatado; componente de cartilagem e dECM; interage com fatores de crescimento",
    concentrationRange: { min: 0.5, max: 5, typical: 2, unit: "% m/v" },
    crosslink: ["chemical", "photo_UV"],
    modulus_kPa: { min: 1, max: 20 },
    poreSize_um: { min: 10, max: 200 },
    printability: ["extrusion"],
    cellViability_24h_pct: 90,
    tissueApplications: ["Cartilagem", "Disco intervertebral"],
    keyReferences: ["Wang 2014 Biomaterials"],
    pros: ["Específica para cartilagem", "Ligação a FGF/TGF"],
    cons: ["Baixa resistência mecânica", "Degradação rápida"],
    typicalPartners: ["collagen_II", "hyaluronic_acid", "gelma"],
    costTier: "medium",
    icon: "🧩",
  },
  {
    id: "laminin",
    name: "Laminina",
    shortName: "Laminin",
    category: "natural",
    family: "MEC protein",
    description: "Glicoproteína de membrana basal; crítica para neural, epitelial e vascular",
    concentrationRange: { min: 0.1, max: 1, typical: 0.3, unit: "% m/v" },
    crosslink: ["physical"],
    modulus_kPa: { min: 0.1, max: 2 },
    poreSize_um: { min: 1, max: 50 },
    printability: ["inkjet"],
    cellViability_24h_pct: 95,
    tissueApplications: ["Neural", "Vascular", "Epitelial", "Muscular"],
    keyReferences: ["Yurchenco 2011 Cold Spring Harb"],
    pros: ["Altamente bioativa", "Motivos IKVAV, YIGSR"],
    cons: ["Muito cara", "Frágil mecanicamente"],
    typicalPartners: ["collagen_IV", "matrigel"],
    costTier: "premium",
    icon: "🕸️",
  },
  {
    id: "collagen_IV",
    name: "Colágeno Tipo IV",
    shortName: "Col-IV",
    category: "natural",
    family: "Collagen",
    description: "Colágeno da membrana basal; forma rede não-fibrilar; suporte para epitélio/endotélio",
    concentrationRange: { min: 0.1, max: 1, typical: 0.3, unit: "% m/v" },
    crosslink: ["physical", "chemical"],
    modulus_kPa: { min: 0.1, max: 5 },
    poreSize_um: { min: 1, max: 20 },
    printability: ["inkjet"],
    cellViability_24h_pct: 93,
    tissueApplications: ["Epitelial", "Endotélio", "Glomerular (rim)"],
    keyReferences: ["Miner 2012 Cold Spring Harb"],
    pros: ["Membrana basal específica", "Suporte endotelial"],
    cons: ["Cara", "Difícil de imprimir sozinho"],
    typicalPartners: ["laminin", "matrigel", "hyaluronic_acid"],
    costTier: "premium",
    icon: "🫘",
  },
  {
    id: "rgd_peptide",
    name: "Peptídeo RGD",
    shortName: "RGD",
    category: "synthetic",
    family: "Peptide",
    description: "Tripeptídeo Arg-Gly-Asp (+ variantes GRGDS); motivo universal de adesão celular via integrinas",
    concentrationRange: { min: 0.01, max: 1, typical: 0.1, unit: "mM funcionalizados" },
    crosslink: ["chemical"],
    modulus_kPa: { min: 0, max: 0 },
    poreSize_um: { min: 0, max: 0 },
    printability: ["extrusion", "DLP_SLA", "inkjet"],
    cellViability_24h_pct: 92,
    tissueApplications: ["Aditivo para adesão celular em PEGDA, alginato"],
    keyReferences: ["Hersel 2003 Biomaterials"],
    pros: ["Converte bioinerte em bioativo", "Reprodutível"],
    cons: ["Aditivo, não constitutivo", "Custo significativo"],
    typicalPartners: ["pegda", "alginate"],
    costTier: "medium",
    icon: "🔗",
  },
  {
    id: "methylcellulose",
    name: "Metilcelulose",
    shortName: "MC",
    category: "natural",
    family: "Cellulose",
    description: "Derivado de celulose; aditivo reológico para shear-thinning; termorreversível",
    concentrationRange: { min: 1, max: 10, typical: 5, unit: "% m/v" },
    crosslink: ["thermal", "physical"],
    modulus_kPa: { min: 1, max: 20 },
    poreSize_um: { min: 10, max: 200 },
    printability: ["extrusion"],
    cellViability_24h_pct: 80,
    tissueApplications: ["Aditivo reológico universal", "Scaffold temporário"],
    keyReferences: ["Schütz 2017 J Tissue Eng"],
    pros: ["Shear-thinning excelente", "Barato"],
    cons: ["Sem bioatividade", "Degradação limitada"],
    typicalPartners: ["alginate", "gelatin"],
    costTier: "low",
    icon: "📄",
  },
]

// Helper de busca rápida
export function getBiomaterialById(id: string): Biomaterial | undefined {
  return BIOMATERIALS.find((b) => b.id === id)
}

// Categorias para filtros na UI
export const BIOMATERIAL_CATEGORIES = [
  { id: "all", label: "Todos", color: "gray" },
  { id: "natural", label: "Naturais", color: "emerald" },
  { id: "synthetic", label: "Sintéticos", color: "blue" },
  { id: "decellularized", label: "Decelularizados (dECM)", color: "rose" },
  { id: "composite", label: "Compósitos/Cerâmicos", color: "amber" },
] as const

// Presets de formulações clássicas (para sugerir ao usuário)
export interface BioinkPreset {
  id: string
  name: string
  tissue: string
  description: string
  components: Array<{ biomaterialId: string; concentration: number; unit: string; role: string }>
  crosslinkProtocol: string
  reference: string
}

export const BIOINK_PRESETS: BioinkPreset[] = [
  {
    id: "alg_gel_standard",
    name: "Alginato + Gelatina (padrão)",
    tissue: "Cartilagem / Genérico",
    description: "Bioink clássico shear-thinning; gelatina dá RGD, alginato dá reticulação rápida com Ca²⁺",
    components: [
      { biomaterialId: "alginate", concentration: 2, unit: "% m/v", role: "Estrutural (crosslinking Ca²⁺)" },
      { biomaterialId: "gelatin", concentration: 5, unit: "% m/v", role: "Bioatividade (RGD)" },
    ],
    crosslinkProtocol: "Pós-impressão: banho CaCl₂ 100 mM por 5 min",
    reference: "Chung et al. 2013 Biomater Sci",
  },
  {
    id: "gelma_ha_cartilage",
    name: "GelMA + HA (cartilagem)",
    tissue: "Cartilagem articular",
    description: "GelMA para estrutura + HA para hidratação; foto-reticulável com LAP",
    components: [
      { biomaterialId: "gelma", concentration: 10, unit: "% m/v", role: "Estrutura crosslinked" },
      { biomaterialId: "hyaluronic_acid", concentration: 1, unit: "% m/v", role: "Hidratação + sinalização CD44" },
    ],
    crosslinkProtocol: "UV 365 nm, 30 s, LAP 0.25% m/v",
    reference: "Schuurman et al. 2013 Macromol Biosci",
  },
  {
    id: "col_fibrin_vascular",
    name: "Colágeno I + Fibrinogênio (vascular)",
    tissue: "Vascular",
    description: "Bioink 100% natural para engenharia vascular; fibrina estimula angiogênese",
    components: [
      { biomaterialId: "collagen_I", concentration: 0.5, unit: "% m/v", role: "Matriz estrutural fibrilar" },
      { biomaterialId: "fibrinogen", concentration: 2, unit: "% m/v", role: "Rede angiogênica" },
    ],
    crosslinkProtocol: "Trombina 5 U/mL + 37°C por 15 min",
    reference: "Kolesky 2016 PNAS",
  },
  {
    id: "gelma_decm_heart",
    name: "GelMA + dECM Cardíaca",
    tissue: "Cardíaco",
    description: "MEC cardíaca + GelMA fornece sinais específicos e estrutura",
    components: [
      { biomaterialId: "gelma", concentration: 7, unit: "% m/v", role: "Estrutura reticulável" },
      { biomaterialId: "decm_cardiac", concentration: 2, unit: "% m/v", role: "Bioatividade específica" },
    ],
    crosslinkProtocol: "UV/visível 405 nm, LAP 0.25% m/v",
    reference: "Das et al. 2019 Acta Biomater",
  },
  {
    id: "pcl_ha_bone",
    name: "PCL + Hidroxiapatita (osso)",
    tissue: "Osso",
    description: "Scaffold termoplástico osteocondutor com reforço cerâmico",
    components: [
      { biomaterialId: "pcl", concentration: 80, unit: "% m/m", role: "Estrutura termoplástica (FDM)" },
      { biomaterialId: "hydroxyapatite", concentration: 20, unit: "% m/m", role: "Osteocondução" },
    ],
    crosslinkProtocol: "Termofusão 80-100°C",
    reference: "Hutmacher 2000 Biomaterials",
  },
  {
    id: "pegda_rgd",
    name: "PEGDA + RGD (DLP)",
    tissue: "Genérico (DLP/SLA)",
    description: "Bioink sintético reprodutível para DLP; RGD para adesão",
    components: [
      { biomaterialId: "pegda", concentration: 15, unit: "% m/v", role: "Estrutura fotocurada" },
      { biomaterialId: "rgd_peptide", concentration: 0.1, unit: "mM", role: "Adesão celular" },
    ],
    crosslinkProtocol: "405 nm DLP, LAP 0.15% m/v",
    reference: "Grigoryan 2019 Science",
  },
]
